# Generated by Django 4.2.3 on 2023-08-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='slot_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slots_request',
            name='catogry',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
