# Generated by Django 4.2.3 on 2023-08-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_slots_slot_color_alter_slots_request_catogry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='slot_color',
            field=models.BooleanField(default=True),
        ),
    ]
