# Generated by Django 4.1.2 on 2023-09-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_slots_request_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots_request',
            name='slot_status',
            field=models.BooleanField(default=True),
        ),
    ]
