# Generated by Django 4.1.2 on 2023-09-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_slots_request_slot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots_request',
            name='payment',
            field=models.ImageField(blank=True, null=True, upload_to='public'),
        ),
    ]
